version: '3.4'

services:
  mariadb_api:
    restart: unless-stopped

  php_api:
    build:
      context: ./docker/php
    restart: unless-stopped
    user: root
    command: |
      /bin/sh -c "
        php-fpm -R
      "
    expose:
      - 9000
    ports:
      - "9000:9000"

  maildev_api:
    restart: unless-stopped
