controllers:
    resource: ../src/Controller/
    type: annotation
    prefix: "%api_route%"

kernel:
    resource: ../src/Kernel.php
    type: annotation

authentication_token:
    path: "%api_route%/login"
    methods: ['POST']
