mercure:
    hubs:
        default:
            url: '%env(MERCURE_URL)%'
            public_url: '%env(MERCURE_PUBLIC_URL)%'
            jwt:
                secret: '%env(MERCURE_SUBSCRIBER_JWT_KEY)%'
                publish: '*'
                subscribe: '*'
                factory: App\Service\Mercure\TokenProvider
